# coding=utf-8
def str_index_enumerated(*l):
    def str_index_enumerate():
        for i, obj in enumerate(l):
            yield str(i), obj
    return list(str_index_enumerate())


CURRENCY_CHOICES = str_index_enumerated(
    "afgani - ؋ (AFN) | Afganistán",
    "lek - L (ALL) | Albania",
    "euro - € (EUR) | Alemania",
    "euro - € (EUR) | Andorra",
    "kuanza de Angola - Kz (AOA) | Angola",
    "rial saudí - ر.س (SAR) | Arabia Saudí",
    "dinar - د.ج (DZD) | Argelia",
    "peso argentino - $ (ARS) | Argentina",
    "dram armenio -   (AMD) | Armenia",
    "florín arubano - ƒ (AWG) | Aruba",
    "dólar australiano - $ (AUD) | Australia",
    "euro - € (EUR) | Austria",
    "manat azerbayano -   (AZN) | Azerbayán",
    "dólar de las Bahamas - $ (BSD) | Bahamas",
    "taka de Bangladés - ৳ (BDT) | Bangladés, Bangladesh",
    "dólar de las Barbados - $ (BBD) | Barbados",
    "dinar de Baréin - .د.ب (BHD) | Baréin, Bahrein",
    "dólar beliceño - $ (BZD) | Belice",
    "rublo bielorruso - Br (BYR) | Bielorrusia, Belarús",
    "kiat de Birmania - K (MMK) | Birmania, Myanmar",
    "boliviano - Bs. (BOB) | Bolivia",
    "marco convertible de Bosnia y Herzegovina - KM (BAM) | Bosnia y Herzegovina",
    "pula de Botsuana - P (BWP) | Botsuana, Botswana",
    "real brasileño - R$ (BRL) | Brasil",
    "dólar de Brunei - $ (BND) | Brunéi",
    "leva búlgaro - лв (BGN) | Bulgaria",
    "franco CFA - Fr (XOF) | Burkina Faso",
    "franco burundés - Fr (BIF) | Burundi",
    "gultrum butanés - Nu. (BTN) | Bután",
    "euro - € (EUR) | Bélgica",
    "escudo de Cabo Verde - Esc, $ (CVE) | Cabo Verde",
    "riel camboyano - ៛ (KHR) | Camboya",
    "dólar canadiense - $ (CAD) | Canadá",
    "rial catarí - ر.ق (QAR) | Catar, Qatar",
    "franco CFA - Fr (XAF) | Chad",
    "peso chileno - $ (CLP) | Chile",
    "yuan, renminbi - ¥, 元 (CNY) | China",
    "euro - € (EUR) | Chipre",
    "euro - € (EUR) | Ciudad del Vaticano",
    "peso colombiano - $ (COP) | Colombia",
    "franco comorano - Fr (KMF) | Comores",
    "won norcoreano - ₩ (KPW) | Corea del Norte",
    "won surcoreano - ₩ (KRW) | Corea del Sur",
    "franco CFA - Fr (XOF) | Costa de Marfil, Côte d'Ivoire",
    "colón costarriqueño - ₡ (CRC) | Costa Rica",
    "kuna croata - kn (HRK) | Croacia",
    "peso cubano - $ (CUP) | Cuba",
    "florín de las Antillas Neerlandesas - ƒ (ANG) | Curação",
    "corona danesa - kr (DKK) | Dinamarca",
    "libra egipcia - £, ج.م (EGP) | Egipto",
    "colón salvadoreño - ₡ (SVC) | El Salvador",
    "dírham - د.إ (AED) | Emiratos Árabes Unidos",
    "nakfa de Eritrea - Nfk (ERN) | Eritrea",
    "euro - € (EUR) | Eslovaquia",
    "euro - € (EUR) | Eslovenia",
    "euro - € (EUR) | España",
    "dólar micronesio - $ (nenhum) | Estados Federados de Micronesia",
    "dólar estadounidense - $ (USD) | Estados Unidos",
    "euro - € (EUR) | Estonia",
    "bir - Br (ETB) | Etiopía",
    "peso filipino - ₱ (PHP) | Filipinas",
    "euro - € (EUR) | Finlandia",
    "euro - € (EUR) | Francia",
    "franco CFA - Fr (XAF) | Gabón",
    "dalasi gambiano - D (GMD) | Gambia",
    "cedi de Gana - ₵ (GHS) | Gana",
    "lari georgiano - ლ (GEL) | Georgia",
    "libra de Gibraltar - £ (GIP) | Gibraltar",
    "euro - € (EUR) | Grecia",
    "quetzal - Q (GTQ) | Guatemala",
    "franco guineano - Fr (GNF) | Guinea",
    "franco CFA - Fr (XAF) | Guinea Ecuatorial",
    "franco CFA - Fr (XOF) | Guinea-Bisáu, Guinea Bissau",
    "gurde - G (HTG) | Haití",
    "lempira - L (HNL) | Honduras",
    "forinto - Ft (HUF) | Hungria",
    "rupia india -   (INR) | India",
    "rupia indonesia - Rp (IDR) | Indonesia",
    "dinar irakí - ع.د (IQD) | Irak",
    "euro - € (EUR) | Irlanda",
    "rial iraní - ﷼ (IRR) | Irán",
    "corona islandesa kr (ISK) | Islandia",
    "dólar de las Islas Caimán - $ (KYD) | Islas Caimán",
    "dólar salomonense - $ (SBD) | Islas Salomón",
    "nuevo séquel - ₪ (ILS) | Israel",
    "euro - € (EUR) | Italia",
    "dólar jamaicano - $ (JMD) | Jamaica",
    "yen - ¥ (JPY) | Japón",
    "dinar jordano - د.ا (JOD) | Jordania",
    "tengue kazajo - ₸ (KZT) | Kazajistán, Kazajstán",
    "chelín keniano - Sh (KES) | Kenia, Kenya",
    "som kirguís - лв (KGS) | Kirguzistán",
    "dinar kuwaití - د.ك (KWD) | Kuwait",
    "kip - ₭ (LAK) | Laos",
    "loti de Lesoto - L (LSL) | Lesoto, Lesotho",
    "lats - Ls (LVL) | Letonia",
    "dólar liberiano - $ (LRD) | Liberia",
    "dinar libio - ل.د (LYD) | Libia",
    "litas - Lt (LTL) | Lituania",
    "euro - € (EUR) | Luxemburgo",
    "libra libanesa - ل.ل (LBP) | Líbano",
    "pataca de Macao - P (MOP) | Macao",
    "denar - ден (MKD) | Macedonia",
    "ariari - Ar (MGA) | Madagascar",
    "ringit - RM (MYR) | Malasia",
    "kuacha de Malaui - MK (MWK) | Malaui, Malawi",
    "rufiya - .ރ (MVR) | Maldivas",
    "franco CFA - Fr (XOF) | Mali",
    "euro - € (EUR) | Malta",
    "dírham - د.م. (MAD) | Marruecos",
    "rupia de Mauricio - ₨ (MUR) | Mauricio",
    "uguiya - UM (MRO) | Mauritania",
    "leu moldavo - L (MDL) | Moldavia",
    "tugrik mongol - ₮ (MNT) | Mongolia",
    "euro - € (EUR) | Montenegro",
    "metical - MT (MZN) | Mozambique",
    "peso mexicano - $ (MXN) | México",
    "euro - € (EUR) | Mónaco",
    "dólar de Namibia - $ (NAD) | Namibia",
    "dólar nauruano - $ (Nenhum) | Nauru",
    "rupia nepalí - ₨ (NPR) | Nepal",
    "córdoba nicaragüense - C$ (NIO) | Nicaragua",
    "naira nigeriano - ₦ (NGN) | Nigeria",
    "corona noruega - kr (NOK) | Noruega",
    "franco CFP - Fr (XPF) | Nueva Caledonia",
    "dólar de Nueva Zelanda - $ (NZD) | Nueva Zelanda",
    "franco CFA - Fr (XOF) | Níger",
    "rial de Omán - ر.ع. (OMR) | Omán",
    "balboa panameño - B/. (PAB) | Panamá",
    "kina - K (PGK) | Papua-Nueva Guiné",
    "rupia pakistaní - ₨ (PKR) | Paquistán ",
    "guaraní paraguayo - ₲ (PYG) | Paraguay",
    "euro - € (EUR) | Países Bajos",
    "nuevo sol peruano - S/. (PEN) | Perú",
    "franco CFP - Fr (XPF) | Polinesia Francesa",
    "złóti - zł (PLN) | Polonia",
    "euro - € (EUR) | Portugal",
    "libra esterlina - £ (GBP) | Reino Unido",
    "franco CFA - Fr (XAF) | República Centroafricana",
    "corona checa - Kč (CZK) | República Checa",
    "franco CFA - Fr (XAF) | República del Congo",
    "franco congoleño - Fr (CDF) | República Democrática del Congo",
    "peso dominicano - $ (DOP) | República Dominicana",
    "franco ruandés - Fr (RWF) | Ruanda, Rwanda",
    "leu rumano - L (RON) | Rumanía",
    "rublo - руб. (RUB) | Rusia",
    "tala - T (WST) | Samoa",
    "dólar del Caribe Oriental - $ (XCD) | San Cristóbal y Nieves, Saint Kitts y Nevis",
    "euro - € (EUR) | San Marino",
    "dólar del Caribe Oriental - $ (XCD) | San Viccente y las Granadinas",
    "dólar del Caribe Oriental - $ (XCD) | Santa Lucía",
    "dobra - Db (STD) Santo Tomé y Príncipe",
    "rupia seychellense - ₨ (SCR) | Seichelles",
    "franco CFA - Fr (XOF) | Senegal",
    "dinar serbio - дин. o din. (RSD) | Serbia",
    "leona - Le (SLL) | Sierra Leona",
    "dólar singapurense - $ (SGD) | Singapur",
    "libra siria - £ o ل.س (SYP) | Siria",
    "chelín somalí - Sh (SOS) | Somalia",
    "rupia ceilandesa - Rs (LKR) | Sri Lanka",
    "lilangeni - L (SZL) | Suazilandia, Swazilandia",
    "rand - R (ZAR) | Sudáfrica",
    "libra sudanesa - £ (SDG) | Sudán",
    "libra sursudanesa - £ (SSP) | Sudán del Sur",
    "corona sueca - kr (SEK) | Suecia",
    "franco suizo - Fr (CHF) | Suiza",
    "dólar surinamés - $ (SRD) | Surinám",
    "bat - ฿ (THB) | Tailandia",
    "nuevo dólar de Taiwán - $ (TWD) | Taiwán",
    "chelín tanzaniano - Sh (TZS) | Tanzania",
    "somoni - ЅМ (TJS) | Tayikistán",
    "franco CFA - Fr (XOF) | Togo",
    "paanga - T$ (TOP) | Tonga",
    "dólar trinitense - $ (TTD) | Trindade e Tobago",
    "manat turcomano - m (TMT) | Turkmenistán",
    "lira turca -   (TRY) | Turquia",
    "dinar tunecino - د.ت (TND) | Túnez",
    "grivna - ₴ (UAH) | Ucrania",
    "chelín ugandés - Sh (UGX) | Uganda",
    "peso uruguayo - $ (UYU) | Uruguay",
    "sum - лв (UZS) | Uzbequistán",
    "vatu do Vanuatu - Vt (VUV) | Vanuatu",
    "bolívar fuerte - Bs F (VEF) | Venezuela",
    "dong - ₫ (VND) | Vietnam",
    "rial yemení - ﷼ (YER) | Yemen",
    "franco yibutiano - Fr (DJF) | Yibuti, Djibouti",
    "kuacha zambiano - ZK (ZMK) | Zambia",
    "dólar zimbabuense - $ (ZWL) | Zimbabue, Zimbabwe",
)
